# Site settings
title: Roberto Peruzzo
seo_title: Roberto Peruzzo - Freelance Web Developer
header-img: img/home-bg.jpg
email: info@robertoperuzzo.it
copyright_name: Roberto Peruzzo
description: > # this means to ignore newlines until "baseurl:"
  Web developer freelance, artigiano del codice, sostenitore della filosofia
  open source e Drupal addicted. Collaboro con aziende, agenzie e altri
  freelance creando software per un web sostenibile.
baseurl: ""
url: "http://robertoperuzzo.it"
linkedin_username: robertoperuzzo
twitter_username: robertoperuzzo
github_username: robertoperuzzo
facebook_username: peruzzo.roberto
email_username: info@robertoperuzzo.it
slideshare_username: robertoperuzzo

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-5332217-14

# Disqus post comments
disqus_website: http-robertoperuzzo-it

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: minima
