# Site settings
title: Roberto Peruzzo
header-img: img/home-bg.jpg
email: hi@robertoperuzzo.it
copyright_name: Roberto Peruzzo
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://robertoperuzzo.github.io"
linkedin_username: robertoperuzzo
twitter_username: robertoperuzzo
github_username: robertoperuzzo
facebook_username: peruzzo.roberto
email_username: hi@robertoperuzzo.it

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: minima
